### ISSUE TITLE
ChapterUID

### ISSUE THREAD

**Issue by hubblec4** [art1pirat/mkvclink#2]
HINT:
ChapterUID is a mandatory element. You don't set these.
Mkvmerge set this missing UID automatically, so it will work for your ChapterAtom also.
But keep in mind it is not correct.

**Comment by art1pirat** [comment]
fixed in [https://github.com/art1pirat/mkvclink/commit/f2d7af6be1b31f579ac1896fe0625869c68cb2e4]
